# Generated by Django 5.1.1 on 2024-10-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='client_photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='therapist_photo',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_photos'),
        ),
    ]
