# Generated by Django 5.1.1 on 2024-10-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_session'),
        ('therapy_sessions', '0002_remove_session_client_remove_session_therapist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
