# Generated by Django 5.1.1 on 2024-10-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0003_delete_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
