# Generated by Django 5.1.1 on 2024-10-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0004_therapysession_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
