# Generated by Django 5.1.1 on 2024-10-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0005_alter_therapysession_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapysession',
            name='price',
        ),
    ]
