# Generated by Django 5.1.1 on 2024-10-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0008_alter_therapysession_options_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapysession',
            options={'ordering': ['-session_date']},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
