# Generated by Django 5.2.3 on 2025-06-28 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessgoal',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='wellnessgoal',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='wellnessgoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnessgoal',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnessgoal',
            name='goal_type',
            field=models.CharField(choices=[('mood', 'Mood Improvement'), ('anxiety', 'Anxiety Reduction'), ('sleep', 'Sleep Quality'), ('exercise', 'Physical Activity'), ('social', 'Social Connection'), ('water', 'Hydration'), ('meditation', 'Meditation'), ('custom', 'Custom Goal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnessgoal',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., minutes, glasses, times', max_length=50),
        ),
        migrations.AlterField(
            model_name='wellnessstreak',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wellnessstreak',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wellnessstreak',
            name='streak_type',
            field=models.CharField(choices=[('reflection', 'Daily Reflection'), ('meditation', 'Meditation'), ('exercise', 'Exercise'), ('water', 'Water Intake'), ('sleep', 'Sleep Goal'), ('social', 'Social Activity')], max_length=20),
        ),
        migrations.CreateModel(
            name='MoodAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_mood', models.DecimalField(decimal_places=2, max_digits=3)),
                ('mood_entries', models.IntegerField(default=0)),
                ('anxiety_level', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sleep_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('activity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('social_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WellnessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('meditation', 'Meditation'), ('exercise', 'Exercise'), ('reading', 'Reading'), ('journaling', 'Journaling'), ('social', 'Social Activity'), ('hobby', 'Hobby'), ('therapy', 'Therapy Session'), ('self_care', 'Self Care'), ('custom', 'Custom Activity')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('mood_before', models.IntegerField(blank=True, choices=[(1, 'Very Sad'), (2, 'Sad'), (3, 'Neutral'), (4, 'Happy'), (5, 'Very Happy')], null=True)),
                ('mood_after', models.IntegerField(blank=True, choices=[(1, 'Very Sad'), (2, 'Sad'), (3, 'Neutral'), (4, 'Happy'), (5, 'Very Happy')], null=True)),
                ('energy_level', models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], null=True)),
                ('completed', models.BooleanField(default=False)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MoodPattern',
        ),
    ]
